name: Deployment

on:

  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  Plan:
    
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY_ID}}
          aws-region: ap-south-1
    
      - name: Init terraform
        run: terraform init
    
      - name: Terraform Plan
        run: |
          terraform plan

  Apply:
    runs-on: ubuntu-latest
    needs: Plan
    environment: tf-apply
    steps:
      - name: TF Apply
        run: terraform apply -auto-approve      
